Assembly changes
jeremycole/hello pull request #4
Opened 2019-10-02 18:48 UTC by LiamCoal

A bunch of fun asm changes:
* Add nasm files for mac and linux (in my opinion, easier to understand)
* Mark the ones that will only compile on mac as so

2019-10-03 00:58 UTC, jeremycole requested changes
Yay! I like new things and it looks like you're doing good work here!!! I still need to read some of the assembly but I went ahead and left a few comments. The highest level ones are probably to move the batch version to another separate PR.

2019-10-03 00:58 UTC, jeremycole commented on hello.bat
> +rem written in batch
```suggestion
rem written in batch script.
```

2019-10-03 00:58 UTC, jeremycole commented on hello.bat
> +)
```suggestion
)

```

(Just end the file with a newline.)

2019-10-03 00:58 UTC, jeremycole commented on hello.linux.nasm
> +        ; the program is no longer running now
```suggestion
        ; the program is no longer running now
        
```

2019-10-03 00:58 UTC, jeremycole commented on hello.bat
> +    echo Hello World
Can you make this message match the one used everywhere else `Hello, World!`? It looks like [batch script has some weird quoting rules](https://www.robvanderwoude.com/escapechars.php) but it should be possible to get it to work, maaaaybe this (but you'll need to try it and see if it outputs what you want):

```suggestion
    echo Hello^, World^^!
```

2019-10-03 00:58 UTC, jeremycole commented on hello.bat
> +@echo off
I think you should move batch script to a separate pull request from assembly!

2019-10-03 00:58 UTC, jeremycole commented on hello.s
> +# Assembly (macho64, gas), only compiles on MacOS
I don't think this description is really right – Mach-O 64 is an executable file format, not an architecture. I should think that this code is x86-64 specific and gas-specific, and probably relies on stdlib for the `_write` syscall wrapper. I am not sure that it's MacOS specific – could you clarify what's specific to Mac OS here?

I think we should make a directory for `assembly` and put all these in there with nice names, like `assembly/hello_x86-64_macos.gas` or so...

I think there are a bunch more we could end up adding. 😄

2019-10-03 00:58 UTC, jeremycole commented on hello.linux.nasm
> +        helloworld_size: dd 14 ; Hard coded, may be improved
This is good – for consistency sake perhaps we should do the same thing you're doing here in the `gas` version as well?

2019-10-03 00:58 UTC, jeremycole commented on hello.linux.nasm
> +        je .exit ; if so jump to _start.exit
This isn't really `_start.exit` is it? I think it's just a label named `.exit`? I think the names are still global, but you tell me, I am definitely ready to be wrong. ;)

2019-10-03 00:58 UTC, jeremycole commented on hello.linux.nasm
> +        dec byte [i] ; Make i go down 1
```suggestion
        dec byte [i] ; Subtract 1 from i
```

2019-10-03 16:36 UTC, LiamCoal commented on hello.linux.nasm
> +        helloworld_size: dd 14 ; Hard coded, may be improved
porbably

2019-10-05 17:17 UTC, LiamCoal commented on hello.linux.nasm
> +        je .exit ; if so jump to _start.exit
The edb tool (assembly debugger) says: jmp hello!_start.exit
```assembly
cmp byte [i], 0
je hello!_start.exit
; ...
jmp hello!_start.loop
```

2019-10-13 00:20 UTC, LiamCoal commented on hello.bat
> +    echo Hello World
```echo Hello^, World^! ``` outputs what you're looking for.
I also noticed that older versions of Windows may not support the LF ending. Maybe CRLF is better.

2019-10-13 00:25 UTC, LiamCoal commented on hello.linux.nasm
> +        je .exit ; if so jump to _start.exit
Fixed for understandability.

2019-10-20 18:46 UTC, LiamCoal commented
i think this pr has been forgotten about :cry:

2019-10-30 01:31 UTC, jeremycole approved these changes
🚀

2019-10-30 01:31 UTC, merged